// src/core/chapters.js — route labels for chapter pickers (menu + in-game main menu)

export const CHAPTERS = [
  { id: "game-menu", label: "Main menu (in-game)" },
  { id: "architect-home", label: "Architect: home" },
  { id: "fabricator-home", label: "Fabricator: home" },
  { id: "fabricator-users", label: "Fabricator: users (admin)" },
  { id: "welcome", label: "Welcome" },
  { id: "hub", label: "Library Hub" },
  { id: "leaderboard", label: "Leaderboard" },
  { id: "architect-requests", label: "Architect: requests & fabricators" },
  { id: "architect-quiz-hub", label: "Architect: quiz hub" },
  { id: "architect-question-edit", label: "Architect: new or edit quiz" },
  { id: "architect-quiz-studio", label: "Architect: quiz composer" },
  { id: "architect-quiz-build", label: "Architect: compose quiz (steps)" },
  { id: "architect-quiz-run", label: "Architect: preview quiz" },
  { id: "architect-quiz-assign", label: "Architect: assign quiz" },
  { id: "architect-wing-assign", label: "Architect: assign narrative wings" },
  { id: "librarian-assigned-quizzes", label: "Attend quiz (architect)" },
  { id: "librarian-quiz-play", label: "Take assigned quiz" },
  { id: "fabricator-queue", label: "Fabricator: request queue" },
  { id: "fabricator-request-detail", label: "Fabricator: request detail" },
  { id: "fabricator-wing-builder", label: "Fabricator: tileset narrative wing" },
  { id: "architect-approval", label: "Architect: approve submissions" },
  { id: "library-world", label: "Explore library (pixel)" },
  { id: "history-1-pre", label: "History (pre-test)" },
  { id: "history-1", label: "History" },
  { id: "history-1-post", label: "History (post-test)" },
  { id: "history-1-delayed", label: "History (delayed test)" },
  { id: "geography-game", label: "Geography", requiresGeography: true }
];
